name: CI

on:
  push:
    branches: ["primary"]
  pull_request:
    branches: ["primary"]

# CI on the "primary" branch opts out of concurrency grouping by using the run's
# unique run_id.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/primary' && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest
          - os: macos-latest
      fail-fast: false

    steps:
      - name: Install tools
        uses: Roblox/setup-foreman@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow-external-github-orgs: true

      - name: Run tests
        run: npm test

  aggregator:
    name: Gated Commits
    runs-on: ubuntu-latest
    needs: [run-tests]
    if: ${{ always() }}
    steps:
      - name: Aggregator
        run: |
          if [ "${{ needs.run-tests.result }}" == "success" ]; then
            echo "Tests passed"
          else
            echo "Tests failed"
            exit 1
          fi
