name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

# CI on the "master" branch opts out of concurrency grouping by using the run's
# unique run_id.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    strategy:
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest
          - os: macos-latest
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"

      - name: Install tools
        uses: Roblox/setup-foreman@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow-external-github-orgs: true

      - name: Install node dependencies
        run: npm install

      - name: Run tests on Linux
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - name: Run tests on non-Linux
        run: npm test
        if: runner.os != 'Linux'

  aggregator:
    name: Gated Commits
    runs-on: ubuntu-latest
    needs: [run-tests]
    if: ${{ always() }}
    steps:
      - name: Aggregator
        run: |
          if [ "${{ needs.run-tests.result }}" == "success" ]; then
            echo "Tests passed"
          else
            echo "Tests failed"
            exit 1
          fi
